---
title: "30daymappinghousingchallenge"
author: "scurry"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: TRUE
    theme: united
    number_sections: FALSE
    toc_float: TRUE
    toc_depth: 2
    code_folding: hide
---

```{r setup, include=FALSE}

setwd("C:/LocalDocuments/GitHub/2024_30daymapchallenge")

knitr::opts_chunk$set(echo = TRUE)

#install.packages("devtools")
devtools::install_github("CityOfPhiladelphia/rphl", force = TRUE)

library(censusapi)
library(cowplot)
library(dplyr)
library(sf)
library(ggplot2)
library(ggtext)
library(glue)
library(lubridate)
library(mapdeck)
library(cartogram)
library(raster)
library(rphl)
library(tidycensus)
library(tidygeocoder)
library(tidyr)
library(tigris)

options(tigris_use_cache = TRUE)

```

```{r basemaps, include=FALSE, message=FALSE, warning=FALSE}

options(tigris_use_cache = TRUE)

map_phl_bound <- places(state = "PA", class = "city", cb = TRUE) %>% 
  filter(NAME == "Philadelphia") %>%
  st_transform("EPSG:2272") %>%
  erase_water()

```


# 30 Day Map(ping Housing) Challenge

Wow, let's give it a go. 

## Day 01 - Points

```{r day01_data, include=FALSE, message=FALSE, warning=FALSE}

query <- paste("SELECT *", "FROM permits")
d01_data <- rphl::get_carto(query = query, format = "csv", base_url = "https://phl.carto.com/api/v2/sql", stringsAsFactors = FALSE)

```

```{r day01_work, message=FALSE, warning=FALSE}

d01_work <- d01_data %>%
  filter(commercialorresidential == "RESIDENTIAL") %>%
  filter(permittype == "DEMOLITION" | permittype == "RESIDENTIAL BUILDING") 

d01_work <- filter(d01_work, grepl("DEMOLITION|NEW CONSTRUCTION", typeofwork)) 

d01_work$mostrecentinsp <- ymd_hms(d01_work$mostrecentinsp)

d01_work <- d01_work %>%
  filter(mostrecentinsp >= "2024-01-01")

d01_work <- d01_work %>%
  distinct(address, .keep_all = TRUE) 

d01_work <- d01_work %>%
  drop_na(geocode_x, geocode_y)

d01_work <- st_as_sf(d01_work, coords = c("geocode_x", "geocode_y"), crs = 2272)

d01_work$type <- if_else(grepl("DEMOLITION", d01_work$typeofwork), "DEMOLITION", "NEW CONSTRUCTION")

table(d01_work$type)

```

```{r day01_map, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}

demo_color <- "#913047"
newcon_color <- "#516954"
day01_title <- "There have been <span style='color: #913047;'>**296 Demolition**</span> and <span style='color: #516954;'>**1,136 New Construction**</span> \n Residential Permits Issued in Philadlephia in 2024"

ggplot() +
  geom_sf(data = map_phl_bound, color = "white", fill = "gray80") +
  geom_sf(data = d01_work, aes(color = type), size = 0.75) +
  scale_color_manual(values = c(demo_color, newcon_color)) +
  labs(subtitle = day01_title,
       caption = "Data Source: OpenDataPhilly, Licenses & Inspections") +
  theme(plot.subtitle = element_textbox_simple(size = 14, lineheight = 1, halign = 0.5, padding = margin(10, 30, 20, 30)),
        plot.caption = element_textbox_simple(size = 6),
        legend.position = "none",
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank())


```

## Day 02 - Lines

```{r day02_data, include=FALSE, message=FALSE, warning=FALSE}

#data <- url("api.census.gov/data/2023/acs/flows?")
#fromotherstate = "B07204_011"

map_states <- states(cb = TRUE) 

#download and clean the headers from this website:
#https://www.census.gov/data/tables/time-series/demo/geographic-mobility/state-to-state-migration.html

# d02_data <- read.csv(file = "C:/LocalDocuments/GitHub/2024_30daymapchallenge/data/State_to_State_Migration_Table_2023_T13.csv", header = TRUE)

d02_data <- get_flows(geography = "county",
                       state = c("PA", "DE", "NJ"),
                       year = 2022,
                       output = "long",
                       geometry = TRUE)


```

```{r day02_work, message=FALSE, warning=FALSE}

d02_work <- d02_data %>%
  group_by(FULL2_NAME) %>%
  summarise(totin = sum(MOVEDIN)) %>%
  rename("MOVEDFROM" = "FULL2_NAME") %>%
  mutate(MOVEDTO = "District") %>%
  filter(MOVEDFROM != "Pennsylvania" & MOVEDFROM != "Delaware" & MOVEDFROM != "New Jersey") %>%
  st_drop_geometry()

map_states <- map_states %>%
  st_transform(crs = 5070)

map_padenj <- map_states %>%
  filter(STUSPS == "PA" | STUSPS == "DE" | STUSPS == "NJ") %>%
  group_by() %>%
  summarise()

map_padenj_ctr <- map_padenj %>%
  st_centroid()

map_padenj_ctr <- extract(map_padenj_ctr, geometry, into = c('Lat', 'Lon'), '\\((.*),(.*)\\)', conv = T)

map_padenj_ctr <- map_padenj_ctr %>%
  mutate(MOVEDTO = "District") %>%
  rename(tolat = "Lat", tolon = "Lon")

map_states_ctr <- map_states %>% 
  st_centroid() %>%
  dplyr::select(NAME) %>%
  rename("MOVEDFROM" = "NAME")

map_states_ctr <- extract(map_states_ctr, geometry, into = c('Lat', 'Lon'), '\\((.*),(.*)\\)', conv = T)

map_states_ctr <- map_states_ctr %>%
  rename(frlat = "Lat", frlon = "Lon")

d02_work_ <- inner_join(d02_work, map_padenj_ctr, by = "MOVEDTO")

d02_work_ <- inner_join(d02_work_, map_states_ctr, by = "MOVEDFROM")

```

```{r day02_map, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}

day02_title <- "New York, Maryland, Florida, and California were the prior homes of over 200,000 new residents who moved to the Third District in 2022"

ggplot() + 
  geom_sf(data = map_states, fill = if_else(map_states$STUSPS == "NY" | map_states$STUSPS == "MD" | map_states$STUSPS == "FL" | map_states$STUSPS == "CA", "lightblue", "gray90"), color = "transparent") +
  geom_sf(data = map_states, fill = "transparent", color = "white", size = 4) +
  geom_sf(data = map_padenj, fill = "darkolivegreen", color = "transparent") +
  geom_curve(data = d02_work_, aes(x = frlat, y = frlon, xend = tolat, yend = tolon), col = "darkslategray4", size = (d02_work_$totin/20000), alpha = 0.5, curvature = 0.2) +
  geom_point(data = d02_work_,
             aes(x = frlat, y = frlon), 
             colour = "darkslategray",
             size = (d02_work_$totin/20000)) +
  geom_point(data = map_padenj_ctr,
             aes(x = tolat, y = tolon), 
             colour = "darkslategray") +
  labs(title = day02_title,
       caption = "Data Source: US Census Bureau, ACS 1-year") +
  theme(plot.title = element_textbox_simple(size = 14, lineheight = 1, halign = 0.5, padding = margin(10, 30, 10, 30)),
        plot.caption = element_textbox_simple(size = 6),
        legend.position = "none",
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks = element_blank()) +
  xlim(-2150000, 2074000) +
  ylim(400000.00, 3500000) 
ggsave(filename = "thumbnails/02_scurry_lines.png", width = 6, height = 6, dpi = 300)

```

## Day 03 - Polygons

```{r day03_data, include=FALSE, message=FALSE, warning=FALSE}

acs_variable_list.2022 <- load_variables(2022, #year
                                         "acs5", #five year ACS estimates
                                         cache = TRUE)

d03_data <- get_acs(geography = "county",
                    state = c("PA", "DE", "NJ"),
                    variables = c(medsmoc = "B25088_002", medhhinc = "B19019_001"), #median smoc w a mortgage
                    year = 2022,
                    geometry = TRUE,
                    output = "wide"
)

```

```{r day03_work, message=FALSE, warning=FALSE}

d03_work <- d03_data %>%
  mutate(monthly_lw = (medsmocE/0.3)) %>%
  mutate(annual_lw = ((monthly_lw*12))) %>%
  mutate(lw_ratio = (medhhincE/annual_lw)) %>%
  st_transform(crs = 2272)

```

```{r day03_map, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}

d03_map <- cartogram_cont(d03_work, weight = "lw_ratio")

day03_title <- "<span style='color: #3288BD;'>McKean County's</span> <span style='color: #FFFFFF;'>Median Household Income is **1.4 times** more than its Cost of Living & </span> <span style='color: #D53E4F;'>Essex County's</span> <span style='color: #FFFFFF;'>Median Household Income is **.58 times** less than its Cost of Living</span>"

day03_subtitle <- "<span style='color: #FFFFFF;'>Cost of Living is calculated as a living wage where 2022 Median Selected Monthly Ownership Costs of homeowners with a mortgage make up 30% of an annual salary</span>"

day03_caption <- "<span style='color: #FFFFFF;'>Data Source: US Census Bureau, ACS 1-year</span>"

ggplot() +
  geom_sf(data = d03_map, aes(fill = lw_ratio), color = "transparent") +
  geom_sf(data = d03_map, fill = "transparent", color = if_else((d03_map$GEOID == "34013" | d03_map$GEOID == "42083"), "black", "transparent")) +
  scale_fill_distiller(palette = "Spectral", direction = 1) +
  labs(title = day03_title,
       subtitle = day03_subtitle,
       caption = day03_caption) +
  theme(plot.background = element_rect(fill = "black"),
        plot.title = element_textbox_simple(size = 14, lineheight = 1, halign = 0.5, padding = margin(10, 60, 10, 60)),
        plot.subtitle = element_textbox_simple(size = 9, lineheight = 1, halign = 0.5, padding = margin (5, 15, 20, 15)),
        plot.caption = element_textbox_simple(size = 6),
        legend.position = "none",
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

ggsave(filename = "thumbnails/03_scurry_polygons.png", width = 6, height = 6, dpi = 300)

```

## Day 04 - Hexagons

```{r day04_data, include=FALSE, message=FALSE, warning=FALSE}

d04_data <- get_acs(geography = "block group",
                    state = "PA",
                    county = "Philadelphia",
                    variables = c(medyrbuilt = "B25035_001", totpop = "B02001_001", 
                                  totwhitepop = "B02001_002", totblackpop = "B02001_003"), #correlate age to race
                    year = 2022,
                    geometry = TRUE,
                    output = "wide"
)

```

```{r day04_work, message=FALSE, warning=FALSE}

d04_work <- d04_data %>%
  mutate(pcentwhite = totwhitepopE/totpopE,
         pcentnonwhite = 1-(totwhitepopE/totpopE),
         pcentblack = totblackpopE/totpopE) %>%
  mutate(coloroldbg = if_else(pcentnonwhite >= 0.50 & medyrbuiltE <= 1970, TRUE, FALSE)) %>%
  st_centroid()

d04_work <- extract(d04_work, geometry, into = c('Lat', 'Lon'), '\\((.*),(.*)\\)', conv = T)

map_phl_bound_4269 <- map_phl_bound %>%
  st_transform(crs = 4269)

```

```{r day04_map, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}

# ggplot(data = d04_work %>%
#          filter(coloroldbg == TRUE), aes(x = Lat, y = Lon)) + 
#   geom_point() 

#Where are there a high concentration of block groups with predominantly nonwhite hh and median home built before 1970
ggplot() + 
  geom_sf(data = map_phl_bound_4269, color = "white", fill = "gray") +
  geom_hex(data = d04_work %>%
         filter(coloroldbg == TRUE), aes(x = Lat, y = Lon), bins = 40, alpha = 0.85) +
  # ylim(39.9, 40.1) +
  # xlim(-75.3, -75) +
  scale_fill_distiller(palette = "Oranges", direction = 1) +
  annotate("text", x = -75.259, y = 40.01, label = "Haddington", color = "#7B452C", size = 3, fontface = "bold") +
  geom_curve(aes(x = -75.259, xend = -75.247, y = 40.005, yend = 39.973), color = "steelblue", size = 0.8, curvature = 0.25) +
#  annotate("text", x = -75.15, y = 39.9, label = "Cobbs Creek", color = "#7B452C", size = 3, fontface = "bold") +
  annotate("text", x = -75.1, y = 39.95, label = "Point Breeze", color = "#E36D26", size = 3, fontface = "bold") +
  geom_curve(aes(x = -75.1, xend = -75.165, y = 39.943, yend = 39.935), color = "steelblue", size = 0.8, curvature = -0.25) +
  labs(title = "High Risks of Lead in Philadelphia",
       subtitle = "Where are the highest concentrations of block groups with predominantly non-White residents and homes built before 1970?",
       caption = "Data Source: US Census Bureau, ACS 1-year") +
  theme(plot.title = element_textbox_simple(size = 14, lineheight = 1, halign = 0.5, padding = margin(10, 30, 5, 30)),
        plot.subtitle = element_textbox_simple(size = 9, lineheight = 1, halign = 0.5, padding = margin(5, 20, 20, 20)),
        plot.caption = element_textbox_simple(size = 6, lineheight = 1, halign = 1),
        legend.position = "none",
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

ggsave(filename = "thumbnails/04_scurry_hexagons.png", width = 6, height = 6, dpi = 300)

# ggplot(data = d04_work, aes(x = medyrbuiltE, y = pcentnonwhite)) + 
#   geom_hex() 

```

## Day 05 - Journey

```{r day05_data, include=FALSE, message=FALSE, warning=FALSE}

#https://www.census.gov/data/tables/2020/demo/metro-micro/commuting-flows-2020.html
#remove headers, footers, and convert Workers in Commuting Flow to Numeric column

d05_data <- read.csv(file = "data/d05_source.csv")

map_states <- states()

map_counties <- counties() 

```

```{r day05_work, message=FALSE, warning=FALSE}

d05_work <- d05_data %>%
  filter(Workers.in.Commuting.Flow > MOE) %>%
  drop_na(W.County.FIPS.Code) %>%
  mutate(R.GEOID = (1000 * R.State.FIPS.Code) + R.County.FIPS.Code,
         W.GEOID = (1000 * W.State.FIPS.Code) + W.County.FIPS.Code) 

map_counties_ctr <- map_counties %>%
  mutate(R.GEOID = as.numeric(GEOID)) %>%
  st_transform(crs = 5070) %>% 
  st_centroid() %>%
  dplyr::select(R.GEOID) 

map_counties_ctr <- tidyr::extract(map_counties_ctr, geometry, into = c('Lat', 'Lon'), '\\((.*),(.*)\\)', conv = T)

map_counties_ctr <- map_counties_ctr %>%
  rename(rlat = "Lat", rlon = "Lon")

d05_work <- inner_join(d05_work, map_counties_ctr, by = "R.GEOID", keep = TRUE)

map_counties_ctr <- map_counties_ctr %>%
  rename(wlat = "rlat", wlon = "rlon", W.GEOID = "R.GEOID")

d05_work <- inner_join(d05_work, map_counties_ctr, by = "W.GEOID", keep = FALSE)

d05_work <- d05_work %>%
  mutate(distmeter = pointDistance(d05_work[,c("rlat", "rlon")], d05_work[,c("wlat", "wlon")], lonlat = FALSE)) %>%
  mutate(distmile = distmeter/1609.34)

d05_work <- d05_work %>%
  filter(W.State.Name != "Hawaii" & W.State.Name != "Alaska" & W.State.Name != "Puerto Rico" &
           R.State.Name != "Hawaii" & R.State.Name != "Alaska" & R.State.Name != "Puerto Rico") %>%
  filter(distmile > 0 & distmile < 480)

ggplot() + 
  geom_histogram(data = d05_work %>%
                   filter(distmile > 0 & distmile < 480), aes(x = distmile), fill = "darkolivegreen4", color = "darkolivegreen", bins = 60)

quantile(d05_work$Workers.in.Commuting.Flow)
quantile(d05_work$distmile)

d05_work <- d05_work %>%
  mutate(flowpercentile = case_when(Workers.in.Commuting.Flow <= quantile(d05_work$Workers.in.Commuting.Flow, 0.25) ~ "u25",
                                Workers.in.Commuting.Flow <= quantile(d05_work$Workers.in.Commuting.Flow, 0.50) ~ "u50",
                                Workers.in.Commuting.Flow <= quantile(d05_work$Workers.in.Commuting.Flow, 0.75) ~ "u75",
                                Workers.in.Commuting.Flow > quantile(d05_work$Workers.in.Commuting.Flow, 0.75) ~ "u100")) %>%
  mutate(distpercentile = case_when(distmile <= quantile(d05_work$distmile, 0.25) ~ "u25",
                                    distmile <= quantile(d05_work$distmile, 0.50) ~ "u50",
                                    distmile <= quantile(d05_work$distmile, 0.75) ~ "u75",
                                    distmile > quantile(d05_work$distmile, 0.75) ~ "u100"))

```

```{r day05_map, message=FALSE, warning=FALSE, fig.width=12, fig.height=6}

#low = "lemonchiffon", mid = "darkolivegreen", high = "royalblue4"

#87AFD5
#4F7EAA
#265480
#0B3155

d05_mapa <- ggplot() + 
  geom_segment(data = d05_work %>%
                 filter(flowpercentile == "u25"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#E5866C", size = 0.25, alpha = 0.75, curvature = 0.0) +
  geom_segment(data = d05_work %>%
                 filter(flowpercentile == "u50"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#8F5443", size = 0.25, alpha = 0.75, curvature = 0.0) +
  geom_segment(data = d05_work %>%
                 filter(flowpercentile == "u75"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#435DBA", size = 0.25, alpha = 0.75, curvature = 0.0) +
  geom_segment(data = d05_work %>%
                 filter(flowpercentile == "u100"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#2E4080", size = 0.25, alpha = 0.75, curvature = 0.0) +
#  scale_color_gradient2(limits = c(0, 50000), low = "lightcyan", high = "royalblue4", transform = "log1p") +
  coord_cartesian(xlim = c(-2150000, 2074000), ylim = c(400000, 3500000)) +
  labs(caption = " ") +
  theme(
    # plot.title = element_textbox_simple(size = 14, lineheight = 1, halign = 0.0, padding = margin(10, 30, 5, 30)),
    #     plot.subtitle = element_textbox_simple(size = 9, lineheight = 1, halign = 0.0, padding = margin(5, 30, 10, 30)),
        plot.caption = element_textbox_simple(size = 6, lineheight = 1, halign = 1),
        legend.position = "bottom",
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

d05_mapb <- ggplot() + 
  geom_segment(data = d05_work %>%
                 filter(distpercentile == "u100"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#2E4080", size = 0.25, alpha = 0.75, curvature = 0.0) +
  geom_segment(data = d05_work %>%
                 filter(distpercentile == "u75"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#435DBA", size = 0.25, alpha = 0.75, curvature = 0.0) +
  geom_segment(data = d05_work %>%
                 filter(distpercentile == "u50"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#8F5443", size = 0.25, alpha = 0.75, curvature = 0.0) + 
  geom_segment(data = d05_work %>%
                 filter(distpercentile == "u25"), aes(x = rlat, y = rlon, xend = wlat, yend = wlon), color = "#E5866C", size = 0.25, alpha = 0.75, curvature = 0.0) +
#  scale_color_gradient2(limits = c(0, 50000), low = "lightcyan", high = "royalblue4", transform = "log1p") +
  coord_cartesian(xlim = c(-2150000, 2074000), ylim = c(400000, 3500000)) +
  labs(caption = "Data Source: US Census Bureau, ACS 5-year, 2016-2020") +
  theme(
    # plot.title = element_textbox_simple(size = 14, lineheight = 1, halign = 0.0, padding = margin(10, 30, 5, 30)),
    #     plot.subtitle = element_textbox_simple(size = 9, lineheight = 1, halign = 0.0, padding = margin(5, 30, 10, 30)),
        plot.caption = element_textbox_simple(size = 6, lineheight = 1, halign = 1),
        legend.position = "bottom",
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

d05_map_plotrow <- plot_grid(d05_mapa, d05_mapb, labels = c("Heaviest Commute Routes", "Shortest Commute Routes"), label_color = c("#2E4080", "#E5866C"), rel_widths = c(6, 6))

d05_map_title <- ggdraw() + 
  draw_label(
    "Pre-COVID Commute Routes between Residences and Workplaces",
    fontface = "bold",
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

plot_grid(
  d05_map_title, d05_map_plotrow,
#  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

ggsave(filename = "thumbnails/05_scurry_journey.png", width = 12, height = 6, dpi = 300)

```

## Day 06 - Raster

```{r day06_data, include=FALSE, message=FALSE, warning=FALSE}



```

```{r day06_work, message=FALSE, warning=FALSE}



```

```{r day06_map, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}



```

# Appendix

## Code That Did Not Work Out
```{r eval=FALSE, include=FALSE}

d04_data <- get_acs(geography = "county",
                    variables = c(avghhsizeoo = "B25010_002", avghhsizero = "B25010_003", 
                                  numbr = "B25041_001"), #median household size owners renters
                    year = 2022,
                    geometry = TRUE,
                    output = "wide"
)

d04_work <- d04_data %>%
  st_centroid()

d04_work <- extract(d04_work, geometry, into = c('Lat', 'Lon'), '\\((.*),(.*)\\)', conv = T)

ggplot(data = d04_work, aes(x = Lat, y = Lon)) + 
  geom_point(aes(color = avghhsizeooE)) +
  xlim(-130, -60) +
  ylim(20, 60)

```

```{r eval=FALSE, include=FALSE}

d04_data <- get_acs(geography = "county",
                    variables = c(medyrbuilt = "B25035_001", totpop = "B02001_001", 
                                  totwhitepop = "B02001_002", totblackpop = "B02001_003"), #correlate age to race
                    year = 2022,
                    geometry = TRUE,
                    output = "wide"
)

d04_work <- d04_data %>%
  mutate(pcentwhite = totwhitepopE/totpopE,
         pcentnonwhite = 1-(totwhitepopE/totpopE),
         pcentblack = totblackpopE/totpopE)

ggplot(data = d04_work, aes(x = medyrbuiltE, y = pcentnonwhite)) + 
  geom_hex() 

```

